[package]
name = "trace-view"
version = "0.0.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
chrono = "0.4.40"
clap = { version = "4.5.31", features = ["derive"] }
crossterm = "0.28.1"
ctrlc = "3.4.5"
derive_more = { version = "2.0.1", features = ["full"] }
ratatui = "0.29.0"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.140"
thiserror = "2.0.12"
